### ISSUE TITLE
Cryptic error message when config keys mismatch the required_config in individual gateway

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#57] opened 2017-12-27 13:32 UTC
Library spits out a weird error message when the key name in the application config does not match the `required_config` of the gateways in lib.

```
** (exit) exited in: GenServer.call(:payment_worker, {:authorize, Gringotts.Gateways.Stripe, 5, nil, [currency: "usd"]}, 5000)
   ** (EXIT) an exception was raised:
       ** (ArgumentError) argument error
           :erlang.byte_size(nil)
           (gringotts) lib/gringotts/gateways/stripe.ex:321: Gringotts.Gateways.Stripe.commit/4
           (gringotts) lib/gringotts/worker.ex:26: Gringotts.Worker.handle_call/3
           (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
           (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
           (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
   (elixir) lib/gen_server.ex:774: GenServer.call/3
```

We can definitely improve this by showing an error message which specifies that we have used wrong key names which are not present in the `use Gringotts.Adapter, required_config: [:secret_key, :default_currency]` of the gateway file.

**Comment by oyeb** [comment] 2017-12-28 06:39
I cannot reproduce this. I tested the following on dev (4306a89),
```elixir
Gringotts.authorize(:payment_worker, Gringotts.Gateways.Stripe, 5, nil, [currency: "usd"])
```
And got a nice message (as has been set in [Adapter](https://github.com/aviabird/gringotts/blob/dev/lib/gringotts/adapter.ex#L27)):
```
** (ArgumentError) expected [:default_currency, :secret_key] to be set, got: nil

    (gringotts) lib/gringotts/gateways/stripe.ex:62: Gringotts.Gateways.Stripe.raise_on_missing_config/2
    (gringotts) lib/gringotts.ex:141: Gringotts.authorize/5
```

Moreover, note that your stacktrace is pointing to an `ArgumentError` in the call to `:erlang.byte_size(nil)` from `stripe.ex:321`, while validating `required_config` happens much before in `validate_config`.

**Comment by oyeb** [comment] 2018-06-04 10:32
Closing as we've got rid of the payment worker and this was not reproducible.

**Closed by oyeb** 2018-06-04 10:32 UTC
Labels: effort1: easy(hours), hotlist: community-help, severity: low
